# Changes here will be overwritten by Copier
_commit: v3.16.0
_src_path: https://github.com/evanharmon1/harmon-init
bunch_add: false
ci_runner: ubuntu-latest
code_owner: evanharmon1
devcontainer: true
git_init: false
github_org: evanharmon1
github_release_init: false
github_remote_create: false
include_ansible: false
include_terraform: false
license: mit
obsidian_project_add: false
project_description: My personal website
project_management: github
project_name: Evan Harmon Website
project_slug: evan-harmon
project_type: web-astro
run_task_install: false
use_release_please: true
