[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[redirects]]
  from = "https://evanharmon.com/memex/*"
  to = "https://publish.obsidian.md/serve?url=evanharmon.com/memex/:splat"
  status = 200
  force = true
